name: Plugin_MFLRP
version: 1.0
main: fr.incendie.Main
api-version: 1.12
author: Incendie
description: Plugin Minecraft pour serveur MFLRP

# Commandes du plugin
commands:
  startfire:
    description: Démarre un incendie autour du joueur avec paramètres
    usage: /<command> <nom> <hauteurMin> <hauteurMax> <tailleMax> <vitessePropagation> <delaiReignition>
    permission: plugin.startfire
  listfires:
    description: Affiche la liste des zones d'incendie actives
    usage: /<command>
    permission: plugin.startfire
  removefire:
    description: Supprime une zone d'incendie par nom
    usage: /<command> <nomZone>
    permission: plugin.startfire
  extinguishitem:
    description: Définit l'objet qui éteindra les incendies au clic droit
    usage: /<command> <materialId> <delaiSecondes>
    permission: plugin.startfire
  extinguishstatus:
    description: Affiche l'item et le delai d'extinction actuellement charges
    usage: /<command>
    permission: plugin.startfire
# Permissions du plugin
permissions:
  plugin.startfire:
    description: Permission pour démarrer un incendie
    default: op
