name: Plugin_MFLRP
version: 1.0
main: fr.incendie.Main
api-version: 1.12
author: Incendie
description: Plugin Minecraft pour serveur MFLRP

# Commandes du plugin
commands:
  startfire:
    description: Démarre un incendie autour du joueur avec paramètres
    usage: /<command> <nom> <hauteurMin> <hauteurMax> <tailleMax>
    permission: plugin.startfire

# Permissions du plugin
permissions:
  plugin.startfire:
    description: Permission pour démarrer un incendie
    default: op
